/*  =========================================================================
    mc_parameter_setvalue_consumer - The submit consumer for the setValue operation
    The setValue operation allows a consumer to set the raw value for one or more parameters

    The MIT License (MIT)
    =========================================================================
*/

#ifndef MC_PARAMETER_SETVALUE_CONSUMER_H_INCLUDED
#define MC_PARAMETER_SETVALUE_CONSUMER_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/mc_parameter_setvalue_consumer.api" to make changes.
//  @interface
//  This API is a draft, and may change without notice.
#ifdef NMFAPI_BUILD_DRAFT_API
#define MC_PARAMETER_SETVALUE_CONSUMER_URI "mc/parameter/consumer/setValue"  // The consumer URI for the setValue operation

//  *** Draft method, for development use, may change without warning ***
//  Instanciate a consumer object for the setValue operation
NMFAPI_EXPORT mc_parameter_setvalue_consumer_t *
    mc_parameter_setvalue_consumer_new (mal_ctx_t *mal_ctx, mal_uri_t *provider_uri);

//  *** Draft method, for development use, may change without warning ***
//  The destructor
NMFAPI_EXPORT void
    mc_parameter_setvalue_consumer_destroy (mc_parameter_setvalue_consumer_t **self_p);

//  *** Draft method, for development use, may change without warning ***
//  Lock the mutex
//  A mutex is used to force a synchronous response despite the request being an asynchronous operation
NMFAPI_EXPORT void
    mc_parameter_setvalue_consumer_mutex_lock (mc_parameter_setvalue_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Unlock the mutex
//  A mutex is used to force a synchronous response despite the request being an asynchronous operation
NMFAPI_EXPORT void
    mc_parameter_setvalue_consumer_mutex_unlock (mc_parameter_setvalue_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Create and initialize the actor
NMFAPI_EXPORT void
    mc_parameter_setvalue_consumer_actor_init (mc_parameter_setvalue_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Get error code from processing the response
NMFAPI_EXPORT int
    mc_parameter_setvalue_consumer_get_response_error_code (mc_parameter_setvalue_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Get the param inst ids MAL message field
NMFAPI_EXPORT long *
    mc_parameter_setvalue_consumer_get_field_param_inst_id_list (mc_parameter_setvalue_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Set the param inst ids MAL message field
NMFAPI_EXPORT void
    mc_parameter_setvalue_consumer_set_field_param_inst_id_list (mc_parameter_setvalue_consumer_t *self, long *param_inst_id_list);

//  *** Draft method, for development use, may change without warning ***
//  Get the param tags MAL message field
NMFAPI_EXPORT unsigned char*
    mc_parameter_setvalue_consumer_get_field_param_tag_list (mc_parameter_setvalue_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Set the param tags MAL message field
NMFAPI_EXPORT void
    mc_parameter_setvalue_consumer_set_field_param_tag_list (mc_parameter_setvalue_consumer_t *self, unsigned char *param_tag_list);

//  *** Draft method, for development use, may change without warning ***
//  Get the param values MAL message field
NMFAPI_EXPORT char **
    mc_parameter_setvalue_consumer_get_field_param_value_list (mc_parameter_setvalue_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Set the param values MAL message field
NMFAPI_EXPORT void
    mc_parameter_setvalue_consumer_set_field_param_value_list (mc_parameter_setvalue_consumer_t *self, char **param_value_list);

//  *** Draft method, for development use, may change without warning ***
//  Get the number of params MAL message field
NMFAPI_EXPORT size_t
    mc_parameter_setvalue_consumer_get_field_param_list_size (mc_parameter_setvalue_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Set the number of params MAL message field
NMFAPI_EXPORT void
    mc_parameter_setvalue_consumer_set_field_param_list_size (mc_parameter_setvalue_consumer_t *self, size_t param_list_size);

#endif // NMFAPI_BUILD_DRAFT_API
//  @end

#ifdef __cplusplus
}
#endif

#endif
