/*  =========================================================================
    mc_parameter_list_definition_consumer - The request consumer for the listDefinition operation.

    The MIT License (MIT)
    =========================================================================
*/

#ifndef MC_PARAMETER_LIST_DEFINITION_CONSUMER_H_INCLUDED
#define MC_PARAMETER_LIST_DEFINITION_CONSUMER_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/mc_parameter_list_definition_consumer.api" to make changes.
//  @interface
//  This API is a draft, and may change without notice.
#ifdef NMFAPI_BUILD_DRAFT_API
#define MC_PARAMETER_LIST_DEFINITION_CONSUMER_URI "mc/parameter/listDefinition/consumer"  // the consumer URI for the listDefinition operation

//  *** Draft method, for development use, may change without warning ***
//  Instanciate a consumer object for the listDefinition operation.
NMFAPI_EXPORT mc_parameter_list_definition_consumer_t *
    mc_parameter_list_definition_consumer_new (mal_uri_t *provider_uri);

//  *** Draft method, for development use, may change without warning ***
//  The destructor.
NMFAPI_EXPORT void
    mc_parameter_list_definition_consumer_destroy (mc_parameter_list_definition_consumer_t **self_p, mal_ctx_t *mal_ctx);

//  *** Draft method, for development use, may change without warning ***
//  Get the param names MAL message field
NMFAPI_EXPORT char **
    mc_parameter_list_definition_consumer_get_field_param_names (mc_parameter_list_definition_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Set the param names MAL message field
NMFAPI_EXPORT void
    mc_parameter_list_definition_consumer_set_field_param_names (mc_parameter_list_definition_consumer_t *self, char **param_names);

//  *** Draft method, for development use, may change without warning ***
//  Get the size of the param names MAL message field
NMFAPI_EXPORT size_t
    mc_parameter_list_definition_consumer_get_field_param_size (mc_parameter_list_definition_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Set the size of the param names MAL message field
NMFAPI_EXPORT void
    mc_parameter_list_definition_consumer_set_field_param_size (mc_parameter_list_definition_consumer_t *self, size_t param_size);

//  *** Draft method, for development use, may change without warning ***
//  Create the consumer actor.
NMFAPI_EXPORT void
    mc_parameter_list_definition_consumer_actor_create (mc_parameter_list_definition_consumer_t *self, mal_ctx_t *mal_ctx);

//  *** Draft method, for development use, may change without warning ***
//  Self test of this class.
NMFAPI_EXPORT void
    mc_parameter_list_definition_consumer_test (bool verbose);

#endif // NMFAPI_BUILD_DRAFT_API
//  @end

#ifdef __cplusplus
}
#endif

#endif
