/*  =========================================================================
    mc_parameter_list_definition_consumer - The request consumer for the listDefinition operation.

    The MIT License (MIT)
    =========================================================================
*/

#ifndef MC_PARAMETER_LIST_DEFINITION_CONSUMER_H_INCLUDED
#define MC_PARAMETER_LIST_DEFINITION_CONSUMER_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/mc_parameter_list_definition_consumer.api" to make changes.
//  @interface
//  This API is a draft, and may change without notice.
#ifdef NMFAPI_BUILD_DRAFT_API
#define MC_PARAMETER_LIST_DEFINITION_CONSUMER_URI "mc/parameter/listDefinition/consumer"  // the consumer URI for the listDefinition operation

//  *** Draft method, for development use, may change without warning ***
//  Instanciate a consumer object for the listDefinition operation
NMFAPI_EXPORT mc_parameter_list_definition_consumer_t *
    mc_parameter_list_definition_consumer_new (mal_ctx_t *mal_ctx, mal_uri_t *provider_uri);

//  *** Draft method, for development use, may change without warning ***
//  The destructor
NMFAPI_EXPORT void
    mc_parameter_list_definition_consumer_destroy (mc_parameter_list_definition_consumer_t **self_p);

//  *** Draft method, for development use, may change without warning ***
//  Clear the response variables
NMFAPI_EXPORT void
    mc_parameter_list_definition_consumer_response_clear (mc_parameter_list_definition_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Lock the mutex
//  A mutex is used to force a synchronous response despite the request being an asynchronous operation
NMFAPI_EXPORT void
    mc_parameter_list_definition_consumer_mutex_lock (mc_parameter_list_definition_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Unlock the mutex
//  A mutex is used to force a synchronous response despite the request being an asynchronous operation
NMFAPI_EXPORT void
    mc_parameter_list_definition_consumer_mutex_unlock (mc_parameter_list_definition_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Create and initialize the actor
NMFAPI_EXPORT void
    mc_parameter_list_definition_consumer_actor_init (mc_parameter_list_definition_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Get response variable for the identity ids
NMFAPI_EXPORT long *
    mc_parameter_list_definition_consumer_get_response_identity_id_list (mc_parameter_list_definition_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Get response variable for the definition ids
NMFAPI_EXPORT long *
    mc_parameter_list_definition_consumer_get_response_definition_id_list (mc_parameter_list_definition_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Get response variable for number elements
NMFAPI_EXPORT size_t
    mc_parameter_list_definition_consumer_get_response_element_count (mc_parameter_list_definition_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Get error code from processing the response
NMFAPI_EXPORT int
    mc_parameter_list_definition_consumer_get_response_error_code (mc_parameter_list_definition_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Get the param names MAL message field
NMFAPI_EXPORT char **
    mc_parameter_list_definition_consumer_get_field_param_name_list (mc_parameter_list_definition_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Set the param names MAL message field
NMFAPI_EXPORT void
    mc_parameter_list_definition_consumer_set_field_param_name_list (mc_parameter_list_definition_consumer_t *self, char **param_names);

//  *** Draft method, for development use, may change without warning ***
//  Get the size of the param names MAL message field
NMFAPI_EXPORT size_t
    mc_parameter_list_definition_consumer_get_field_param_name_list_size (mc_parameter_list_definition_consumer_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Set the size of the param names MAL message field
NMFAPI_EXPORT void
    mc_parameter_list_definition_consumer_set_field_param_name_list_size (mc_parameter_list_definition_consumer_t *self, size_t param_names_size);

#endif // NMFAPI_BUILD_DRAFT_API
//  @end

#ifdef __cplusplus
}
#endif

#endif
