#!/bin/bash

PROJECT_DIR="$(cd "$(dirname "$0")" && cd .. && pwd)"
echo "### Generate MAL/C from $PROJECT_DIR"
LIB_DIR=$PROJECT_DIR/local
SRC_DIR=$PROJECT_DIR/malc

if  [ $# -ne 0 ]; then
  CMD=$1
else
  CMD="simple"
fi

genmake_clean() {
  echo "=== clean : $PWD"
  rm -f aclocal.m4 configure.ac libtool Makefile.in
  rm -f autogen.sh config.log *.cmake
  rm -f config.status Makefile
  rm -f CMakeLists.txt configure Makefile.am test-suite.log
  rm -rf config doc autom4te.cache
}

genmake_all() {
  echo "=== generate : $PWD"
  ./generate.sh
  check
  echo "=== autogen"
  ./autogen.sh
  check
  echo "=== configure"
  ./configure --prefix=$LIB_DIR
  check
  echo "=== make"
  make
  check
  echo "=== make check"
  make check
  check
  echo "=== make install"
  make install
  check
}

genmake_simple() {
  echo "=== make"
  make
  check
  echo "=== make check"
  make check
  check
  echo "=== make install"
  make install
  check
}

genmake() {
  if [ $CMD == "all" ]; then
    genmake_all
  else
    if [ $CMD == "clean" ]; then
      genmake_clean
    else
      genmake_simple
    fi
  fi
}

check() {
if  [ $? -ne 0 ]; then
    echo "ERROR in $PWD" 1>&2
    exit 1
fi
}

cd $SRC_DIR/util;
genmake

cd $SRC_DIR/malattributes;
genmake

cd $SRC_DIR/malbinary;
genmake

cd $SRC_DIR/mal;
genmake

cd $SRC_DIR/malzmq;
genmake

cd $SRC_DIR/malactor;
genmake

cd $SRC_DIR/test/testarea;
genmake

#cd $SRC_DIR/test/simple_app;
#genmake

#cd $SRC_DIR/test/send_app;
#genmake

#cd $SRC_DIR/test/submit_app;
#genmake

#cd $SRC_DIR/test/request_app;
#genmake

#cd $SRC_DIR/test/invoke_app;
#genmake

cd $SRC_DIR/test/progress_app;
genmake

#cd $SRC_DIR/test/pubsub_app;
#genmake
