#!/bin/bash

PROGDIR=`cd "$(dirname "$0")" >/dev/null; pwd`
echo "genmakeall PROGDIR=${PROGDIR}"

echo "### Generate MAL/C from $PROGDIR to $MAL_LOCAL"

# TODO: Stop when an error occurs

cd $PROGDIR/util;
./genmake $*

cd $PROGDIR/malattributes;
./genmake $*

cd $PROGDIR/mal;
./genmake $*

cd $PROGDIR/malbinary;
./genmake $*

cd $PROGDIR/malzmq;
./genmake $*

cd $PROGDIR/maltcp;
./genmake $*

cd $PROGDIR/malactor;
./genmake $*

cd $PROGDIR/test/testarea;
./genmake $*

#cd $PROGDIR/test/simple_app;
#./genmake $*

#cd $PROGDIR/test/send_app;
./genmake $*

#cd $PROGDIR/test/submit_app;
./genmake $*

#cd $PROGDIR/test/request_app;
./genmake $*

#cd $PROGDIR/test/invoke_app;
./genmake $*

cd $PROGDIR/test/progress_app;
./genmake $*

#cd $PROGDIR/test/pubsub_app;
#./genmake $*

# TODO: If clean should remove $MAL_LOCAL or print a message
