#!/bin/bash

PROGDIR=`cd "$(dirname "$0")" >/dev/null; pwd`
echo "genmakeall PROGDIR=${PROGDIR}"

# MAL_HOME should be the directory containing the MAL/C source directory.

# Only set MAL_HOME if not already set
[ -z "$MAL_HOME" ] && MAL_HOME=`cd "${PROGDIR}/.." >/dev/null; pwd`

# MAL_LOCAL is the installation directory for MAL/C libraries and includes.
# Normally it is $MAL_HOME/local for an installattion limited to the developer,
# it could be /usr/local for a global installation. 

# Only set MAL_LOCAL if not already set
[ -z "$MAL_LOCAL" ] && MAL_LOCAL=${MAL_HOME}/local

echo "### Generate MAL/C from $MAL_HOME to $MAL_LOCAL"

#Stop when an error occurs
check() {
if  [ "$?" -ne "0" ]; then
    echo "ERROR in $PWD" 1>&2
    exit 1
fi
}

# Should remove $MAL_LOCAL -> print a message
if  [ "$#" -ne "0" ]; then
  if [ $1 == "distclean" ]; then
    echo ""
    echo "!! May be you should clean $MAL_LOCAL target directory !!"
    echo ""
  fi
fi

genmake_mal() {
  cd $PROGDIR/malutil;
  ./genmake $*
  check

  cd $PROGDIR/malattributes;
  ./genmake $*
  check

  cd $PROGDIR/mal;
  ./genmake $*
  check

  cd $PROGDIR/malbinary;
  ./genmake $*
  check

  cd $PROGDIR/malsplitbinary;
  ./genmake $*
  check

  cd $PROGDIR/malzmq;
  ./genmake $*
  check

  cd $PROGDIR/maltcp;
  ./genmake $*
  check

  cd $PROGDIR/malactor;
  ./genmake $*
  check
}

genmake_apps() {
  cd $PROGDIR/apps/generated_areas;
  ./genmake $*
  check

  cd $PROGDIR/apps/nmfapi-c;
  ./genmake $*
  check

  cd $PROGDIR/apps/demo;
  ./genmake $*
  check
}

genmake_tests() {
  cd $PROGDIR/test/testarea;
  ./genmake $*
  check

  cd $PROGDIR/test/encoding;
  ./genmake $*
  check

#  cd $PROGDIR/test/simple_app;
#  ./genmake $*
#  check

  cd $PROGDIR/test/send_app;
  ./genmake $*
  check

  cd $PROGDIR/test/submit_app;
  ./genmake $*
  check

  cd $PROGDIR/test/request_app;
  ./genmake $*
  check

  cd $PROGDIR/test/invoke_app;
  ./genmake $*
  check

  cd $PROGDIR/test/progress_app;
  ./genmake $*
  check

  cd $PROGDIR/test/pubsub_app;
  ./genmake $*
  check

  cd $PROGDIR/test/malzmq_pubsub_app;
  ./genmake $*
  check
}

# build and selftest malc libs
genmake_mal $*

# build and selftest malc test apps
genmake_tests $*

# build amd selftest malc apps
genmake_apps $*
