#ifndef __MC_AGGREGATION_AGGREGATIONDEFINITIONDETAILS_H_INCLUDED__
#define __MC_AGGREGATION_AGGREGATIONDEFINITIONDETAILS_H_INCLUDED__

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus


// fields accessors for composite mc_aggregation_aggregationdefinitiondetails
mal_string_t * mc_aggregation_aggregationdefinitiondetails_get_description(mc_aggregation_aggregationdefinitiondetails_t * self);
void mc_aggregation_aggregationdefinitiondetails_set_description(mc_aggregation_aggregationdefinitiondetails_t * self, mal_string_t * f_description);
mal_uoctet_t mc_aggregation_aggregationdefinitiondetails_get_category(mc_aggregation_aggregationdefinitiondetails_t * self);
void mc_aggregation_aggregationdefinitiondetails_set_category(mc_aggregation_aggregationdefinitiondetails_t * self, mal_uoctet_t f_category);
mal_duration_t mc_aggregation_aggregationdefinitiondetails_get_reportinterval(mc_aggregation_aggregationdefinitiondetails_t * self);
void mc_aggregation_aggregationdefinitiondetails_set_reportinterval(mc_aggregation_aggregationdefinitiondetails_t * self, mal_duration_t f_reportinterval);
mal_boolean_t mc_aggregation_aggregationdefinitiondetails_get_sendunchanged(mc_aggregation_aggregationdefinitiondetails_t * self);
void mc_aggregation_aggregationdefinitiondetails_set_sendunchanged(mc_aggregation_aggregationdefinitiondetails_t * self, mal_boolean_t f_sendunchanged);
mal_boolean_t mc_aggregation_aggregationdefinitiondetails_get_senddefinitions(mc_aggregation_aggregationdefinitiondetails_t * self);
void mc_aggregation_aggregationdefinitiondetails_set_senddefinitions(mc_aggregation_aggregationdefinitiondetails_t * self, mal_boolean_t f_senddefinitions);
mal_boolean_t mc_aggregation_aggregationdefinitiondetails_get_filterenabled(mc_aggregation_aggregationdefinitiondetails_t * self);
void mc_aggregation_aggregationdefinitiondetails_set_filterenabled(mc_aggregation_aggregationdefinitiondetails_t * self, mal_boolean_t f_filterenabled);
mal_duration_t mc_aggregation_aggregationdefinitiondetails_get_filteredtimeout(mc_aggregation_aggregationdefinitiondetails_t * self);
void mc_aggregation_aggregationdefinitiondetails_set_filteredtimeout(mc_aggregation_aggregationdefinitiondetails_t * self, mal_duration_t f_filteredtimeout);
mal_boolean_t mc_aggregation_aggregationdefinitiondetails_get_generationenabled(mc_aggregation_aggregationdefinitiondetails_t * self);
void mc_aggregation_aggregationdefinitiondetails_set_generationenabled(mc_aggregation_aggregationdefinitiondetails_t * self, mal_boolean_t f_generationenabled);
mc_aggregation_aggregationparameterset_list_t * mc_aggregation_aggregationdefinitiondetails_get_parametersets(mc_aggregation_aggregationdefinitiondetails_t * self);
void mc_aggregation_aggregationdefinitiondetails_set_parametersets(mc_aggregation_aggregationdefinitiondetails_t * self, mc_aggregation_aggregationparameterset_list_t * f_parametersets);

// default constructor
mc_aggregation_aggregationdefinitiondetails_t * mc_aggregation_aggregationdefinitiondetails_new(void);

// encoding functions related to transport malbinary
int mc_aggregation_aggregationdefinitiondetails_add_encoding_length_malbinary(mc_aggregation_aggregationdefinitiondetails_t * self, mal_encoder_t * encoder, void * cursor);
int mc_aggregation_aggregationdefinitiondetails_encode_malbinary(mc_aggregation_aggregationdefinitiondetails_t * self, mal_encoder_t * encoder, void * cursor);
int mc_aggregation_aggregationdefinitiondetails_decode_malbinary(mc_aggregation_aggregationdefinitiondetails_t * self, mal_decoder_t * decoder, void * cursor);

// destructor
void mc_aggregation_aggregationdefinitiondetails_destroy(mc_aggregation_aggregationdefinitiondetails_t ** self_p);

// test function
void mc_aggregation_aggregationdefinitiondetails_test(bool verbose);

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // __MC_AGGREGATION_AGGREGATIONDEFINITIONDETAILS_H_INCLUDED__
