/*  =========================================================================
    demo - generated layer of public API

    The MIT License (MIT)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef DEMO_LIBRARY_H_INCLUDED
#define DEMO_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <util.h>
#include <malattributes.h>
#include <mal.h>
#include <malbinary.h>
#include <malsplitbinary.h>
#include <malzmq.h>
#include <maltcp.h>
#include <malactor.h>
#include <generated_areas.h>

//  DEMO version macros for compile-time API detection
#define DEMO_VERSION_MAJOR 1
#define DEMO_VERSION_MINOR 0
#define DEMO_VERSION_PATCH 0

#define DEMO_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define DEMO_VERSION \
    DEMO_MAKE_VERSION(DEMO_VERSION_MAJOR, DEMO_VERSION_MINOR, DEMO_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined DEMO_STATIC
#       define DEMO_EXPORT
#   elif defined DEMO_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define DEMO_EXPORT __declspec(dllexport)
#       else
#           define DEMO_EXPORT
#       endif
#   elif defined DEMO_EXPORTS
#       define DEMO_EXPORT __declspec(dllexport)
#   else
#       define DEMO_EXPORT __declspec(dllimport)
#   endif
#   define DEMO_PRIVATE
#elif defined (__CYGWIN__)
#   define DEMO_EXPORT
#   define DEMO_PRIVATE
#else
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define DEMO_PRIVATE __attribute__ ((visibility ("hidden")))
#       define DEMO_EXPORT __attribute__ ((visibility ("default")))
#   else
#       define DEMO_PRIVATE
#       define DEMO_EXPORT
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  DEMO_BUILD_DRAFT_API
#define DEMO_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef DEMO_BUILD_DRAFT_API
typedef struct _demo_app_consumer_t demo_app_consumer_t;
#define DEMO_APP_CONSUMER_T_DEFINED
#endif // DEMO_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef DEMO_BUILD_DRAFT_API
#include "demo_app_consumer.h"
#endif // DEMO_BUILD_DRAFT_API

#ifdef DEMO_BUILD_DRAFT_API

#ifdef __cplusplus
extern "C" {
#endif

//  Self test for private classes
DEMO_EXPORT void
    demo_private_selftest (bool verbose, const char *subtest);

#ifdef __cplusplus
}
#endif
#endif // DEMO_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
