/*  =========================================================================
    mc_parameter_get_value_consumer - The request consumer for the getValue operation.

    The MIT License (MIT)
    =========================================================================
*/

#ifndef MC_PARAMETER_GET_VALUE_CONSUMER_H_INCLUDED
#define MC_PARAMETER_GET_VALUE_CONSUMER_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/mc_parameter_get_value_consumer.api" to make changes.
//  @interface
//  This API is a draft, and may change without notice.
#ifdef NMF_API_BUILD_DRAFT_API
#define MC_PARAMETER_GET_VALUE_CONSUMER_NETWORK_ZONE "Network Zone"  // the consumer actor network zone for the getValue operation
#define MC_PARAMETER_GET_VALUE_CONSUMER_SESSION_NAME_LIVE "LIVE"  // the consumer actor session name for the getValue operation
#define MC_PARAMETER_GET_VALUE_CONSUMER_URI "mc/parameter/getValue/consumer"  // the consumer URI for the getValue operation

//  *** Draft method, for development use, may change without warning ***
//  Instanciate a consumer object for the getValue operation.
NMF_API_EXPORT mc_parameter_get_value_consumer_t *
    mc_parameter_get_value_consumer_new (mal_uri_t *provider_uri);

//  *** Draft method, for development use, may change without warning ***
//  The destructor.
NMF_API_EXPORT void
    mc_parameter_get_value_consumer_destroy (mc_parameter_get_value_consumer_t **self_p, mal_ctx_t *mal_ctx);

//  *** Draft method, for development use, may change without warning ***
//  Create the consumer actor.
NMF_API_EXPORT void
    mc_parameter_get_value_consumer_actor_create (mc_parameter_get_value_consumer_t *self, mal_ctx_t *mal_ctx);

//  *** Draft method, for development use, may change without warning ***
//  Self test of this class.
NMF_API_EXPORT void
    mc_parameter_get_value_consumer_test (bool verbose);

#endif // NMF_API_BUILD_DRAFT_API
//  @end

#ifdef __cplusplus
}
#endif

#endif
