/*  =========================================================================
    sepp_tm - generated layer of public API

    The MIT License (MIT)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef SEPP_TM_LIBRARY_H_INCLUDED
#define SEPP_TM_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <malutil.h>
#include <malattributes.h>
#include <mal.h>
#include <malbinary.h>
#include <malsplitbinary.h>
#include <malzmq.h>
#include <maltcp.h>
#include <malactor.h>
#include <generated_areas.h>
#include <nmfapi_c.h>

//  SEPP_TM version macros for compile-time API detection
#define SEPP_TM_VERSION_MAJOR 1
#define SEPP_TM_VERSION_MINOR 0
#define SEPP_TM_VERSION_PATCH 0

#define SEPP_TM_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define SEPP_TM_VERSION \
    SEPP_TM_MAKE_VERSION(SEPP_TM_VERSION_MAJOR, SEPP_TM_VERSION_MINOR, SEPP_TM_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined SEPP_TM_STATIC
#       define SEPP_TM_EXPORT
#   elif defined SEPP_TM_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define SEPP_TM_EXPORT __declspec(dllexport)
#       else
#           define SEPP_TM_EXPORT
#       endif
#   elif defined SEPP_TM_EXPORTS
#       define SEPP_TM_EXPORT __declspec(dllexport)
#   else
#       define SEPP_TM_EXPORT __declspec(dllimport)
#   endif
#   define SEPP_TM_PRIVATE
#elif defined (__CYGWIN__)
#   define SEPP_TM_EXPORT
#   define SEPP_TM_PRIVATE
#else
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define SEPP_TM_PRIVATE __attribute__ ((visibility ("hidden")))
#       define SEPP_TM_EXPORT __attribute__ ((visibility ("default")))
#   else
#       define SEPP_TM_PRIVATE
#       define SEPP_TM_EXPORT
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  SEPP_TM_BUILD_DRAFT_API
#define SEPP_TM_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef SEPP_TM_BUILD_DRAFT_API
typedef struct _shell_cmd_dispatcher_t shell_cmd_dispatcher_t;
#define SHELL_CMD_DISPATCHER_T_DEFINED
typedef struct _shell_stdout_parser_t shell_stdout_parser_t;
#define SHELL_STDOUT_PARSER_T_DEFINED
typedef struct _shell_proxy_t shell_proxy_t;
#define SHELL_PROXY_T_DEFINED
typedef struct _sepp_tm_utils_t sepp_tm_utils_t;
#define SEPP_TM_UTILS_T_DEFINED
#endif // SEPP_TM_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef SEPP_TM_BUILD_DRAFT_API
#include "shell_cmd_dispatcher.h"
#include "shell_stdout_parser.h"
#include "shell_proxy.h"
#include "sepp_tm_utils.h"
#endif // SEPP_TM_BUILD_DRAFT_API

#ifdef SEPP_TM_BUILD_DRAFT_API

#ifdef __cplusplus
extern "C" {
#endif

//  Self test for private classes
SEPP_TM_EXPORT void
    sepp_tm_private_selftest (bool verbose, const char *subtest);

#ifdef __cplusplus
}
#endif
#endif // SEPP_TM_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
