#ifndef __MC_AGGREGATION_AGGREGATIONDEFINITION_H_INCLUDED__
#define __MC_AGGREGATION_AGGREGATIONDEFINITION_H_INCLUDED__

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus


// fields accessors for composite mc_aggregation_aggregationdefinition
mal_identifier_t * mc_aggregation_aggregationdefinition_get_name(mc_aggregation_aggregationdefinition_t * self);
void mc_aggregation_aggregationdefinition_set_name(mc_aggregation_aggregationdefinition_t * self, mal_identifier_t * f_name);
mal_string_t * mc_aggregation_aggregationdefinition_get_description(mc_aggregation_aggregationdefinition_t * self);
void mc_aggregation_aggregationdefinition_set_description(mc_aggregation_aggregationdefinition_t * self, mal_string_t * f_description);
mc_aggregation_aggregationcategory_t mc_aggregation_aggregationdefinition_get_category(mc_aggregation_aggregationdefinition_t * self);
void mc_aggregation_aggregationdefinition_set_category(mc_aggregation_aggregationdefinition_t * self, mc_aggregation_aggregationcategory_t f_category);
mal_boolean_t mc_aggregation_aggregationdefinition_get_generationenabled(mc_aggregation_aggregationdefinition_t * self);
void mc_aggregation_aggregationdefinition_set_generationenabled(mc_aggregation_aggregationdefinition_t * self, mal_boolean_t f_generationenabled);
mal_duration_t mc_aggregation_aggregationdefinition_get_updateinterval(mc_aggregation_aggregationdefinition_t * self);
void mc_aggregation_aggregationdefinition_set_updateinterval(mc_aggregation_aggregationdefinition_t * self, mal_duration_t f_updateinterval);
mal_boolean_t mc_aggregation_aggregationdefinition_get_filterenabled(mc_aggregation_aggregationdefinition_t * self);
void mc_aggregation_aggregationdefinition_set_filterenabled(mc_aggregation_aggregationdefinition_t * self, mal_boolean_t f_filterenabled);
mal_duration_t mc_aggregation_aggregationdefinition_get_filteredtimeout(mc_aggregation_aggregationdefinition_t * self);
void mc_aggregation_aggregationdefinition_set_filteredtimeout(mc_aggregation_aggregationdefinition_t * self, mal_duration_t f_filteredtimeout);
mc_aggregation_aggregationreference_list_t * mc_aggregation_aggregationdefinition_get_parametersets(mc_aggregation_aggregationdefinition_t * self);
void mc_aggregation_aggregationdefinition_set_parametersets(mc_aggregation_aggregationdefinition_t * self, mc_aggregation_aggregationreference_list_t * f_parametersets);

// default constructor
mc_aggregation_aggregationdefinition_t * mc_aggregation_aggregationdefinition_new(void);

// encoding functions related to transport malbinary
int mc_aggregation_aggregationdefinition_add_encoding_length_malbinary(mc_aggregation_aggregationdefinition_t * self, mal_encoder_t * encoder, void * cursor);
int mc_aggregation_aggregationdefinition_encode_malbinary(mc_aggregation_aggregationdefinition_t * self, mal_encoder_t * encoder, void * cursor);
int mc_aggregation_aggregationdefinition_decode_malbinary(mc_aggregation_aggregationdefinition_t * self, mal_decoder_t * decoder, void * cursor);

// destructor
void mc_aggregation_aggregationdefinition_destroy(mc_aggregation_aggregationdefinition_t ** self_p);

// test function
void mc_aggregation_aggregationdefinition_test(bool verbose);

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // __MC_AGGREGATION_AGGREGATIONDEFINITION_H_INCLUDED__
